config/routes.rb
Rails.application.routes.draw do
  root to: "cities#index"
  
  get     "/about",         to:"pages#about"
  get     "cities/:id",     to:"cities#forecast",     as:"city"
  post    "cities",         to:"cities#create"
  get "*path",              to:"pages#not_found"
  
  resources :cities,        only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
require 'json'
require 'rest-client'

class City < ApplicationRecord

    self.inheritance_column = nil
    before_save     :to_lower_name
    validates       :name, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 40}
    validates       :key, presence: true

    BASIC_URL = "http://dataservice.accuweather.com"
    @apikey = ENV['API_KEY']

    class << self
        def get_key(name)
            url = "#{BASIC_URL}/locations/v1/cities/search?apikey=#{@apikey}&q=#{name}"
            response = RestClient.get(url) { |response, request, result| response }

            if response.length > 0
                json = JSON.parse response.to_s
                city_key = json[0]['Key']
            else
                @city.errors.full_messages.each do |msg|
                    flash[:danger] = msg
                end
            end
        end

        def get_today(key)
            url = "#{BASIC_URL}/forecasts/v1/daily/1day/#{key}?apikey=#{@apikey}"
            response = RestClient.get(url)
            json = JSON.parse response.to_s
        end

        def get_forecast(key)
            url = "#{BASIC_URL}/forecasts/v1/daily/5day/#{key}?apikey=#{@apikey}&details=true"
            response = RestClient.get (url)
            json = JSON.parse response.to_s
        end

        def get_city_image(name)
            url = "https://api.teleport.org/api/urban_areas/slug:#{name}/images/"
            response = RestClient.get (url) { |response, request, result| response }

            if response.code == 200
                json = JSON.parse response.to_s
                url_link = json['photos'][0]['image']['web']
            else
                url_link = "https://www.publicdomainpictures.net/pictures/280000/nahled/not-found-image-15383864787lu.jpg"
            end
        end
        
    end

    private
    def to_lower_name
        name.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def index
      @city = City.new
      @cities = City.all
      @temp = {}
      
      @cities.each do |city|
        get_data = City.get_today(city.key)
        res = {
          min: (( get_data['DailyForecasts'][0]['Temperature']['Minimum']['Value'] - 32 ) * 5/9).round,
          max: (( get_data['DailyForecasts'][0]['Temperature']['Maximum']['Value'] - 32 ) * 5/9).round,
          text: get_data['Headline']['Text']
        }
        @temp[city.key] = (res)
      end
      puts @temp
    end
  
    def create
      @city = City.new(city_params)
      key = City.get_key(@city.name)
      @city.key = key
  
      respond_to do |format|
        if @result = @city.save
          format.html { redirect_to root_url }
          format.js
        else
          format.html {
            @city.errors.full_messages.each do |msg|
              flash[:danger] = msg
            end
            redirect_to root_url
          }
          format.js
        end
      end
  
    end
  
    def destroy
  
      @city = City.find(params[:id])
  
      respond_to do |format|
        if @result = @city.destroy()
          format.html { redirect_to root_url }
          format.js
        else
          format.html {
            @city.errors.full_messages.each do |msg|
              flash[:danger] = msg
            end
            redirect_to root_url
          }
          format.js
        end
      end
      
    end
  
    def forecast
      @city = City.find(params[:id])
      @forecast = City.get_forecast(@city.key)
      @filtered_data = []
      @max_temps = []
      @days_list = []
      
  
      @forecast['DailyForecasts'].each do |day|
        day = {
          date: day['Date'].scan(/.{1,10}/)[0],
          minimum: (( day['Temperature']['Minimum']['Value'] - 32 ) * 5/9).round,
          minimum_phrase: day['RealFeelTemperatureShade']['Minimum']['Phrase'],
          maximum: (( day['Temperature']['Maximum']['Value'] - 32 ) * 5/9).round,
          maximum_phrase: day['RealFeelTemperatureShade']['Maximum']['Phrase'],
          phrase: day['Day']['LongPhrase'],
          precipitacion_probability: day['Day']['PrecipitationProbability'],
          nubosity: day['Day']['CloudCover'],
          icon: day['Day']['Icon']
        }
        @filtered_data.push(day)
        @max_temps.push({name: day[:date], data: day[:maximum]})
        @days_list.push(day[:date])
      end
  
  
  
      puts "prueba"
      puts @filtered_data
      puts "---------------------------------------------------------------"
      puts @max_temps
      puts "---------------------------------------------------------------"
      puts @days_list
      puts "end"
  
    end
  
    def completed_tasks
      render json: Task.group_by_day(:completed_at).count
    end
  
    private
      def city_params
        params.require(:city).permit(:name)
      end
    
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper

    def data
        array = [20,30, "today is fine"]
    end

    def cincodias
        array = [20,30, 40,50, "today is fine"]
    end

    def image(name)
        unless !name.match(/\s/)
            name = name.gsub(' ', '-')
        end
        res = City.get_city_image(name)
    end

    # def get_icon(num)
    #     data = `/assets/#{num}.png`
    #     res = data.to_s
    # end


    # def temp(key)
    #     res = City.get_today(key)
    #     temps = [
    #         (( res['DailyForecasts'][0]['Temperature']['Minimum']['Value'] - 32 ) * 5/9).round,
    #         (( res['DailyForecasts'][0]['Temperature']['Maximum']['Value'] - 32 ) * 5/9).round,
    #         res['Headline']['Text']
    #     ]
    # end

    # def forecast(key)
    #     res = City.get_forecast(key)
    # end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cities/_city.html.erb
<div class="col-sm-6" style="width: 25%; margin-top: 2rem; margin-bottom: 1rem;">
  <div class="card">
    <div class="image">
      <img src=<%= image(city.name) %> class="card-img-top" alt="city.name">
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= city.name.to_s.titleize %></h5>
      <div class="temps" style="display: flex; flex-direction: column; margin-bottom: 15px;">
        <span>Min: <%= @temp[city.key][:min] %></span>
        <span>Max: <%= @temp[city.key][:max] %></span>
        <span>Text: <%= @temp[city.key][:text] %></span>
      </div>
      <div class="buttons" style="display: flex; flex-direction: row; justify-content: space-around;">
        <%= link_to "5-Day Forecast", city_path(city.id), class:'btn btn-primary' %>
        <%= button_to 'Close', city, method: :delete, class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: @city, id: 'add-city') do |form| %>
  <div class="form-inline">
    <%= form.text_field :name, placeholder: t('menu.add.city_name'), class: "form-control mr-sm-2", autocomplete: "off" %>
    <%= form.submit t('menu.add.add_city'), :class => 'btn' %>
  </div>
<% end %>

app/views/cities/_graphic.html.erb
<div class="graphics">
    <h1>graphic</h1>

    <br><hr>
    <span><%= @max_temps %></span>
    
</div>

app/views/cities/_select.html.erb
<div class="select">
  <h1>select</h1>

  <%= image_tag ('/assets/11.png') %>
  <span><%= @days_list %></span>

</div>

app/views/cities/create.js.erb
<% if @result %>
  $('#add-city')[0].reset();
  $('#errors').empty();
  $('.scroll').append("<%= j render @city %>");
  console.log("Successfully added <%= @city.name.capitalize %>.")
<% else %>
  $('#add-city')[0].reset();
  $('#errors').html('<%= j render 'shared/error_messages', object: @city %>');
<% end %>

app/views/cities/destroy.js.erb
<% if @result %>
  $('#errors').empty();
  $('#<%= css_id(@city.name) %>-col').remove();
  console.log("Successfully removed <%= @city.name.capitalize %>.")
<% else %>
  $('#errors').html('<%= j render 'shared/error_messages', object: @city %>');
<% end %>

app/views/cities/forecast.html.erb
<div class="forecast">
    <%= link_to 'Back', :back %>
    
    <div class="header">
        <h1>5 Day Forecast of: <%= @city.name.to_s.titleize %></h1>
    </div>
    <hr>
    
    <div class="view">
        <%= render 'cities/select' %>
        <%= render 'cities/graphic' %>
    </div>
    <hr>

</div>

app/views/cities/index.html.erb
<div class="row"><%= render @cities %></div>

app/views/layouts/_errors_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <%= content_tag(:div, msg, class: "alert alert-danger") %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark justify-content-between">
    <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
    <div>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li>
          <%= link_to t('app.menu.about'), about_path, class:"nav-item" %>
        </li>
      </ul>
    </div>
  <%= render 'cities/form' %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails - WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <div id="errors">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>